M48
; DRILL file {KiCad (6.0.7)} date Sun Nov 13 21:56:28 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-13T21:56:28+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0433
%
G90
G05
T1
X5.0Y-3.4
T2
X4.5Y-3.45
X4.5Y-3.55
X4.5Y-3.65
X4.8Y-3.25
X4.8Y-3.8
X4.9Y-3.25
X4.9Y-3.8
X5.15Y-3.45
X5.15Y-3.55
X5.15Y-3.65
T0
M30
